/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminAcrescimosRouteImport } from './routes/admin/acrescimos'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEntregasRouteImport } from './routes/admin/entregas'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcrescimosRoute = AdminAcrescimosRouteImport.update({
  id: '/acrescimos',
  path: '/acrescimos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/admin/acrescimos': typeof AdminAcrescimosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/admin/acrescimos': typeof AdminAcrescimosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/admin/acrescimos': typeof AdminAcrescimosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/admin/acrescimos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/admin/acrescimos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/admin/acrescimos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/entregas'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acrescimos': {
      id: '/admin/acrescimos'
      path: '/acrescimos'
      fullPath: '/admin/acrescimos'
      preLoaderRoute: typeof AdminAcrescimosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcrescimosRoute: typeof AdminAcrescimosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEntregasRoute: typeof AdminEntregasRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcrescimosRoute: AdminAcrescimosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEntregasRoute: AdminEntregasRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
